### ISSUE TITLE
Propojení s novou databází

### ISSUE THREAD

**Issue by janavit** [daniel-madera/BPDP#2]

**Comment by daniel-madera** [comment]
Nepamatujete si prosím, za jakým účelem jsme chtěli informaci od p. Kopesckeho o studijním programu u studentů?

**Comment by daniel-madera** [comment]
Koukal jsem na view, které jsme dostali a hlavně na data. Našel jsem problém, že například Tomáš Křížek a další jsou uvedeni jak v zaměstnancích tak ve studentech. Jak já poznám, že se jedná o studenta či zaměstnance? Možnost je taková, že bychom umožnili jak zadávat témata, tak se na ně přihlašovat všem, kteří jsou vedeni jako studenti a zároveň zaměstnanci. Co na to říkáte? 

Ještě je možnost to rozdělit právě na základě studijních programů...

**Comment by janavit** [comment]
... Tomáš a jemu podobní:-) by mali byť z pohľadu bpdp študenti - asi preto
sme tam chceli tie štúdijné programy. Ten kto môže vypisovať témy, nemůže
na FM študovať bakalára ani magistra (aspoň dúfam, že tu nikto taký nie je)

2015-10-13 20:27 GMT+02:00 Daniel Maděra <notifications@github.com>:

**Comment by daniel-madera** [comment]
Je možné někde zjistit názvy ústavů a jejich čísla? 
MTI má 7630
... atd.? 
Popřípadě ještě lepší by bylo poprosit pana Kopeschkeho, zda by nám ještě do zaměstnaneckého view nepřidal zkratku ústavu, abychom měli aktuální data o ústavech a nemuseli udržovat vlastní seznam ústavů.

**Comment by janavit** [comment]
... zistím a opýtam sa.

JV

2015-10-16 15:23 GMT+02:00 Daniel Maděra <notifications@github.com>:

**Comment by daniel-madera** [comment]
Propojení studenta s oborem kvůli třídění prací pro garanty.
