### ISSUE TITLE
Ikony a detail témat

### ISSUE THREAD

**Issue by janavit** [daniel-madera/BPDP#21]
Zrušit zašktávaní o oficiálním zadání u vytvoření tématu.

**Comment by janavit** [comment]
Detaily
Pro volné/čekající: Stav, Vedoucí práce, Ústav, Školní rok, Doporučené typy prác, Doporučené obory, Abstrakt
Pro přiřazené: Stav, Vedoucí práce, Ústav, Školní rok, Typ práce, Student, Abstrakt

**Comment by janavit** [comment]
Ikony
Pro volné: 
- editovat téma, kopírovat téma, smazat téma (upozornit, že se smaže všechno - téma, oficiální zadání i student), skrýt téma
- oficiální zadání
- přiřadit studenta (nové okno - výběr ze studentů a výběr z typů)

Pro čekající:
- kopírovat téma
- oficiální zadání

Pro přiřazené:
- kopírovat téma, smazat téma (upozornit, že se smaže všechno - téma, oficiální zadání i student)
- oficiální zadání, pdf
- odebrat studenta

Ikony v archíve:
- kopírování tématu resp. i oficiálního zadání, pokud bude oficiální zadání, tak i pdf

Ikona pre superusera:
- vrátit z dokončeného stavu
- v dokončeném stavu = stav archiv

**Comment by daniel-madera** [comment]
Ikony
Pro volné:
editovat téma, kopírovat téma, smazat téma (upozornit, že se smaže všechno - téma, oficiální zadání), skrýt téma
oficiální zadání
informovat studenta (nové okno - výběr ze emailu studentů), zrušit to z vytváření tématu

Pro čekající:
kopírovat téma
oficiální zadání
Pro přiřazené:

kopírovat téma (dotaz zda chce vyprázdnit pole oficiálního zadání), smazat téma (upozornit, že se smaže všechno - téma, oficiální zadání i student)
oficiální zadání
odebrat studenta
Ikony v archíve:

kopírování tématu resp. i oficiálního zadání, pokud bude oficiální zadání
PDF
Ikona pre superusera:

v dokončeném stavu = stav archiv

**Comment by daniel-madera** [comment]
Není akce kopírování témat a generování PDF v archivu mých témat

**Comment by janavit** [comment]
... ostatní učitelia aj admin to tam majú. Ja nie.

2016-02-25 11:26 GMT+01:00 Daniel Maděra <notifications@github.com>:

**Comment by janavit** [comment]
... ostatní učitelia aj admin to tam majú. Ja nie.
![bug](https://cloud.githubusercontent.com/assets/11853684/13528267/1f1de022-e215-11e5-9ee0-1e753d7294c4.png)
