### ISSUE TITLE
U kopírování témata, zkopírovat i oficiální zadání, pokud existuje.

### ISSUE THREAD

**Issue by janavit** [daniel-madera/BPDP#4]
Důležité, aby učitelé nepřišli o minuloroční zadání, pokud chtějí uvolnit přiřazeného studenta, který práci nakonec neodevzdal. Nebo chtějí stejné zadání vypsat i příští rok.

**Comment by daniel-madera** [comment]
Narazil jsem na problém. Budu muset změnit návrh databáze.

**Comment by daniel-madera** [comment]
Ještě musím řádně otestovat.
