### ISSUE TITLE
Nefunkčné pravidlá Shibboleth (NTI Honza Stebl)

### ISSUE THREAD

**Issue by janavit** [daniel-madera/BPDP#5]
Popísať pravidlá aj do wiki.

**Comment by janavit** [comment]
... bola som za p. Kmochom, vyzerá to, že pre ou=CXI sa začnú postupne objavovať aj cn. Tomášovi Martincovi pribudlo cn=CXI a Janovi Stebelovi zase cn=INT.

**Comment by daniel-madera** [comment]
Ano, viděl jsem to v logu. Dělám menší úpravu, která nahradí předávaní ústav Shibbolethem jiným pomocí konfigurace. Tzn.  ('OVP' -> 'MTI', 'CXI' -> 'MTI', 'INT' -> 'MTI'). Popřípadě v app/Config/config.php lze nastavit jiné nahrazující ústavy.

**Comment by daniel-madera** [comment]
Ještě mě čeká popsání pravidel do wiki, takže ISSUE ještě uzavírat nebudu. Ale jak napovídá label status:resolved je chyba opravená a nahrál jsem ji i na produkční server jak napovídá uzavřený pull request. https://github.com/daniel-madera/BPDP/pull/6

**Comment by daniel-madera** [comment]
Pravidla jsou dopsána do wiki.
