### ISSUE TITLE
Vytvoření a zobrazení zaměření (doplňujících kritérií)

### ISSUE THREAD

**Issue by daniel-madera** [daniel-madera/BPDP#7]
Able to set order of filter criterias at creation.

**Comment by janavit** [comment]
Při vytváření zaměření, doplnit možnost přehazovat pořadí (šipka hore, šipka dole). Při jejich zobrazení pak výsledné pořadí zachovat (u vytváření témy i u filtrování). 
![uploads/d0bdf70e-db38-4fd9-be06-fe18e8582c1a/zmenaPoradie.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd0bdf70e-db38-4fd9-be06-fe18e8582c1a%2FzmenaPoradie.png)

**Comment by daniel-madera** [comment]
Vyřešeno tak, že výchozím stavu jsou doplňující kritéria tříděna dle data modifikace od nejstaršího po nejnovější. Pokud je bude někdo chtít setřídit postupně všechny modifikuje v pořadí, které požaduje.
