### ISSUE TITLE
Otestovat archivaci všech zadání a témat

### ISSUE THREAD

**Issue by daniel-madera** [daniel-madera/BPDP#8]

**Comment by janavit** [comment]
Potrebujem testovacích študentov a učiteľov.

**Comment by daniel-madera** [comment]
Pár jsem jich vytvořil. Lze to i přímo z aplikace - nastavení -> uživatelé -> vytvořit nového uživatele.

**Comment by janavit** [comment]
Ešte počkám, keď bude dorobený rok, za ktorý sa archivuje.
